### ISSUE TITLE
Potential bug/limitation with the add connected service features

### ISSUE THREAD

**Issue by tangollama** [newrelic/nr1-observability-maps#29] opened 2020-07-24 17:33 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

See the feedback in the Explorers Hub [here](https://discuss.newrelic.com/t/nr1-observability-maps-nerdpack/93091/9). Per the message:

## Steps to Reproduce

In one account we have some apps that roll up to a second APM app. If I add a single service to a new map and the right click on that node and add connected services I get this roll up app as a node along with many others. They all have links. Now if I go to remove the roll up node (because its not a real app) it is removed and all the links from other services are also removed. I have tried deleting the node from the map and also from the menu item and both ways removes the links between services. Net result is for the 50+ apps that roll up to a single app I cannot use the add connected services feature and that takes all the fun out of magically creating a map

## Expected Behaviour

Being able to remove upper-level node without losing the links between services.

## Your Environment

v. 0.6.6

**Comment by Kav91** [comment] 2020-07-25 03:26
I'm not sure I fully understand this situation. But I'll explain the current and intended behaviour. 

If a service is added to a map -> this is a real app/entity.
When add connected services is clicked, it will add any relationships to that entity and the corresponding links between them.
If you delete the app/node that you just clicked add connected services from, it has to clean up the links between those newly connected services and that app. 

eg. I've created a very messy map, starting with Fulfilment Service.
Then expanded a few more services.
![image](https://user-images.githubusercontent.com/13043208/88447706-a0a8c080-ce79-11ea-9f39-efc5e4dce4d5.png)

If I delete Fulfilment service, links between other services are still retained, and only links to Fulfilment service has been cleaned up.

![image](https://user-images.githubusercontent.com/13043208/88447711-c59d3380-ce79-11ea-8e1f-fd49a18e9d7d.png)

Links cannot dangle freely without source and target nodes.

**Comment by ricegi** [comment] 2020-07-29 16:16
Have confirmed the behaviour where deleting a connecting service drops the links between nodes. Getting more details from the reporter.

**Comment by ricegi** [comment] 2020-07-29 16:23
The node delete the triggers the links to disappear is actually a roll-up service in APM

**Comment by Kav91** [comment] 2020-08-10 16:24
#34 may resolve this, however I can't confirm as I can't replicate what was shown in the video shared internally.
Need an export of the map config to confirm/further debug.

**Comment by Kav91** [comment] 2020-08-17 03:09
Closing appears to have been resolved.

**Closed by Kav91** 2020-08-17 03:09 UTC
Labels: enhancement, needs review
